[phases.install]
onlyIncludeFiles = [
  ".npmrc",
  ".yarn/releases/yarn-3.4.1.cjs",
  ".yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs",
  ".yarnrc.yml",
  "yarn.lock",
  "turbo.json",
  "package.json", 
  "apps/web/package.json",
  "packages/config/package.json",
  "packages/config/eslint-preset.js",
  "packages/config/prettier-preset.js",
  "packages/eslint-plugin/package.json",
  "packages/core/package.json",
  "packages/ui/package.json",
  "packages/dayjs/package.json",
  "packages/lib/package.json",
  "packages/types/package.json",
  "packages/tsconfig/package.json",
  "packages/trpc/package.json",
  "packages/emails/package.json",
  "packages/features/auth/package.json",
  "packages/features/ee/package.json",
  "packages/features/package.json",
  "packages/prisma/package.json",
  "packages/app-store-cli/package.json",
  "packages/app-store/package.json",
  "packages/app-store/googlevideo/package.json",
  "packages/app-store/around/package.json",
  "packages/app-store/weather_in_your_calendar/package.json",
  "packages/app-store/riverside/package.json",
  "packages/app-store/caldavcalendar/package.json",
  "packages/app-store/ping/package.json",
  "packages/app-store/exchange2016calendar/package.json",
  "packages/app-store/discord/package.json",
  "packages/app-store/google-tag-manager/package.json",
  "packages/app-store/plausible/package.json",
  "packages/app-store/zoomvideo/package.json",
  "packages/app-store/wordpress/package.json",
  "packages/app-store/sirius_video/package.json",
  "packages/app-store/sendgrid/package.json",
  "packages/app-store/exchangecalendar/package.json",
  "packages/app-store/zapier/package.json",
  "packages/app-store/huddle01video/package.json",
  "packages/app-store/jitsivideo/package.json",
  "packages/app-store/stripepayment/package.json",
  "packages/app-store/vital/package.json",
  "packages/app-store/amie/package.json",
  "packages/app-store/office365video/package.json",
  "packages/app-store/office365calendar/package.json",
  "packages/app-store/sylapsvideo/package.json",
  "packages/app-store/vimcal/package.json",
  "packages/app-store/giphy/package.json",
  "packages/app-store/tandemvideo/package.json",
  "packages/app-store/typeform/package.json",
  "packages/app-store/pipedream/package.json",
  "packages/app-store/hubspot/package.json",
  "packages/app-store/ga4/package.json",
  "packages/app-store/n8n/package.json",
  "packages/app-store/campfire/package.json",
  "packages/app-store/raycast/package.json",
  "packages/app-store/telegram/package.json",
  "packages/app-store/closecom/package.json",
  "packages/app-store/fathom/package.json",
  "packages/app-store/rainbow/package.json",
  "packages/app-store/facetime/package.json",
  "packages/app-store/whereby/package.json",
  "packages/app-store/salesforce/package.json",
  "packages/app-store/routing-forms/package.json",
  "packages/app-store/googlecalendar/package.json",
  "packages/app-store/larkcalendar/package.json",
  "packages/app-store/dailyvideo/package.json",
  "packages/app-store/wipemycalother/package.json",
  "packages/app-store/applecalendar/package.json",
  "packages/app-store/qr_code/package.json",
  "packages/app-store/exchange2013calendar/package.json",
  "packages/app-store/signal/package.json",
  "packages/app-store/whatsapp/package.json",
  "packages/app-store/cron/package.json",
  "packages/app-store/zohocrm/package.json",
  "packages/embeds/embed-snippet/package.json",
  "packages/embeds/embed-react/package.json",
  "packages/embeds/embed-core/package.json",
  "packages/app-store-cli/src/build.ts",
  "packages/app-store-cli/src/constants.ts",
  "packages/app-store-cli/src/utils/getAppName.ts",
]
