[phases.install]
onlyIncludeFiles = [
  ".npmrc",
  ".yarn/releases/yarn-3.4.1.cjs",
  ".yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs",
  ".yarnrc.yml",
  "yarn.lock",
  "turbo.json",
  "package.json", 
  "apps/web/package.json",
  "apps/storybook/package.json",
  "apps/swagger/package.json",
  "apps/docs/package.json",
]
